### ISSUE TITLE
Tools not installed in Images

### ISSUE THREAD

**Issue by ved009** [attacksurge/ax#16]
Hello,

Some of the tools like xnlinkfinder are not installed. Checked in all the profiles - default, extras, reconftw and barebones the installation command is not present

**Comment by 0xtavian** [comment]
Hey @ved009, just because the module exists doesn’t mean the tool will be installed. 


To install tools, please see https://ax.attacksurge.com/fundamentals/scans/modules/adding-simple-modules. 

Closing this issue but don’t hesitate to lmk if you have any questions!
