### ISSUE TITLE
getting this error during installation

### ISSUE THREAD

**Issue by zealsham** [attacksurge/ax#2]
manage_auto_update:24: no such file or directory: /Users/shammah/.axiom/interact/includes/.auto_update
Auto-update has been enabled.
Configuring your cloud account...
/dev/fd/11:626: no such file or directory: /Users/shammah/.axiom/interact/axiom-account-setup
ls: /Users/shammah/.axiom/axiom.json: No such file or directory
Adding axiom_rsa key to Packer builder
/dev/fd/11:634: no such file or directory:
mv: rename /Users/shammah/.axiom/tmp.json to : No such file or directory
/dev/fd/11:635: no such file or directory: /Users/shammah/.axiom/configs/authorized_keys
Beginning first packer build...
/dev/fd/11:683: no such file or directory: /Users/shammah/.axiom/interact/axiom-build
You may need to restart your shell: /bin/zsh

**Comment by 0xtavian** [comment]
Hey @zealsham, how did you install? Can you `rm $HOME/.axiom` and try again using the easy install oneliner?

https://ax-framework.gitbook.io/wiki/overview/installation-guide

**Comment by zealsham** [comment]
ive done that severally and no avail

**Comment by zealsham** [comment]
```Your Packer provosioner must be located in /Users/shammah/.axiom/images/pkr.hcl/provisioners/. Make sure to move it```

meanwhile the docs says 

```Custom Provisioners: All Provisioners need to be stored in ~/.axiom/images/provisioners/ and should end with.json```

**Comment by 0xtavian** [comment]
@zealsham 

> ive done that severally and no avail

What OS are you using (Mac? What version?) and how are you installing? Your original post showed errors that indicate to me that ax wasn’t installed correctly. All the missing files etc. You’ll have to make sure ax configure runs without issue before building will succeed. 

If all else fails, try installing in a docker container with the docker install one liner we have in the readme or spin up a fresh Ubuntu 24.04 on any cloud provider and install the controller on that. 



> `Your Packer provosioner must be located in /Users/shammah/.axiom/images/pkr.hcl/provisioners/. Make sure to move it`
> 
> meanwhile the docs says
> 
> `Custom Provisioners: All Provisioners need to be stored in ~/.axiom/images/provisioners/ and should end with.json`

yes I’ll fix this in the documentation. Now that we support both JSON and HCL Provisioners, your provisioner will either have to be in `$HOME/.axiom/images/pkr.hcl/provisioners/` for pkr.hcl or `$HOME/.axiom/images/json/provisioners/`for JSON. I’ll make sure to change that in the wiki. Thanks! But before you get this far, you have to make sure ax configure worked without issue and your cloud account properly configured. Feel free to join our discord as well.

**Comment by 0xtavian** [comment]
Closing this issue. If you are still experiencing problems, lmk.
