### ISSUE TITLE
Scaleway Support?

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [attacksurge/ax#3]
Hey, thanks for this : ) I was wondering if it's possible to add Scaleway.

Thanks

**Comment by 0xtavian** [comment]
Will look into it!

**Comment by 0xtavian** [comment]
@Sh4d0wHunt3rX First pass at scaleway here https://github.com/attacksurge/ax/tree/scaleway! Still a little WIP. lmk if you get a chance to try it!

**Comment by 0xtavian** [comment]
@Sh4d0wHunt3rX please run `ax update`. Then run `ax account-setup` and enter scaleway! 

Closing this issue but don’t hesitate to lmk if you run into any issues. Scaleway is a lot of fun. Happy to have added them as an officially supported cloud provider!
