### ISSUE TITLE
Module jaeles

### ISSUE THREAD

**Issue by jarek-bir** [attacksurge/ax#5]
Hello there. I have been tried to use jaeles module but is no working.I have check  op/go/bin/ and jaeles also is missing .The axiom version was ok with jaeles .Thanks

**Comment by 0xtavian** [comment]
Hi @jarek-bir,

We have moved jaeles install to the extras [HCL](https://github.com/attacksurge/ax/blob/master/images/pkr.hcl/provisioners/extras.pkr.hcl) and [JSON](https://github.com/attacksurge/ax/blob/master/images/json/provisioners/extras.json) provisioners. 

To build extras run `ax build extras`

Closing this issue but lmk if you run into any trouble!
