### ISSUE TITLE
Building from source

### ISSUE THREAD

**Issue by D3vil0p3r** [attacksurge/ax#6]
[Manual Installation](https://ax.attacksurge.com/overview/installation-guide#manual) only explains how to install ax on the current user scope, that is just a clone on `$HOME/.axiom/`.

What if an admin wants to install it at system-level for all users? What if a packager wants to install the framework to a `DESTDIR=` as occurs for example by using `make`?

**Comment by 0xtavian** [comment]
Hi @D3vil0p3r, 
Unfortunately, installing axiom system-wide is not supported atm, neither is changing the default install directory.
