### ISSUE TITLE
nuclei module .axiom/modules/nuclei.json uses wrong syntax for jsonl output

### ISSUE THREAD

**Issue by colemanjp** [attacksurge/ax#7]
I believe the command should be -jle not -jsonl in current versions of nuclei, like this: 

`"command": "/home/op/go/bin/nuclei -update -silent ; cat input | /home/op/go/bin/nuclei -t _folder_ -jle output",`

`-jle, -jsonl-export string    file to export results in JSONL(ine) format`

**Comment by 0xtavian** [comment]
@colemanjp thanks! Will fix it tonight :)
